language: python

python:
  - "2.7"

before_script:
  - psql -c 'create database openbudgets;' -U postgres

before_install:
  - export CI=true

install:
  - pip install -r requirements.txt

script: coverage run --source='.' manage.py test accounts api contexts entities interactions international pages sheets tools commons transport

notifications:
  email:
    - paulywalsh@gmail.com
    - maggotfish@gmail.com

on_success: always

on_failure: always

after_success:
  - coverage report
  - pip install --quiet --use-mirrors python-coveralls
  - coveralls
